# Generated by Django 3.2.16 on 2024-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='days_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
