# Generated by Django 3.2.16 on 2024-12-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_subscription_days_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='days_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
