# Generated by Django 3.2.16 on 2024-12-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_subscription_days_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='days_remaining',
            field=models.FloatField(default=0),
        ),
    ]
