# Generated by Django 3.2.16 on 2024-12-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_subscription_days_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
