# Generated by Django 3.2.16 on 2024-12-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_subscription_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expiration_time',
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
