# Generated by Django 3.2.16 on 2024-12-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20241226_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
