# Generated by Django 3.2.16 on 2024-12-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20241226_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='expiration_time',
            new_name='activation_time',
        ),
    ]
