# Generated by Django 3.2.16 on 2024-12-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_rename_expiration_time_subscription_activation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='activation_time',
            new_name='activated_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='days_remaining',
        ),
        migrations.AddField(
            model_name='subscription',
            name='time_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
