# Generated by Django 3.2.16 on 2024-12-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20241227_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='activated_at',
            new_name='start_time',
        ),
    ]
