# Generated by Django 3.2.16 on 2024-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_rename_activated_at_subscription_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
