# Generated by Django 3.2.16 on 2024-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_subscription_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active_subs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['price', 'status'], name='services_su_price_4147db_idx'),
        ),
    ]
