# Generated by Django 3.2.16 on 2024-12-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20241227_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantitySubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_subs', models.PositiveIntegerField(blank=True, default='0')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active_subs',
        ),
    ]
