# Generated by Django 3.2.16 on 2024-12-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20241228_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuantitySubscriptions',
        ),
    ]
