# Generated by Django 3.2.16 on 2024-12-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.companyname'),
        ),
    ]
